sudo: required
services:
  - docker

before_install:
  - docker build -t george/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run george/react-test npm test -- --coverage

after_success:
  - docker build -t georgeobr/multi-client ./client
  - docker build -t georgeobr/multi-nginx ./nginx
  - docker build -t georgeobr/multi-server ./server
  - docker build -t georgeobr/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
  - docker push georgeobr/multi-client
  - docker push georgeobr/multi-nginx
  - docker push georgeobr/multi-server
  - docker push georgeobr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-ci"
  env: "TestCi-env"
  bucket_name: "elasticbeanstalk-us-east-1-861109070356"
  bucket_path: "test-ci"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


